[template]
src = "sql-virtual_mailbox_domains.cf.template"
dest = "/etc/postfix/sql/sql-virtual_mailbox_domains.cf"
owner = "root"
group = "root"
keys = [
  "/mysql/db",
  "/mysql/user",
  "/mysql/password",
  "/mysql/host",
]