build:
 stage: build
 script:
   - docker-compose -f docker-compose.yml -f compose/mailstack.yml -f compose/mailstack-build.yml -f compose/web-build.yml -f compose/docservice.yml -f compose/docservice-build.yml build
   
test:
 stage: test
 script:
   - bash dockerfiles/testDockerfile.sh
   
deploy:
 stage: deploy
 only:
  refs:
    - master
 script:
   - docker-compose -f docker-compose.yml -f compose/mailstack.yml -f compose/mailstack-build.yml -f compose/web-build.yml -f compose/docservice.yml -f compose/docservice-build.yml push