workflow:
  rules:
    - if: $RUN_CI_PIPELINE == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - when: always

.docker:
  tags:
    - docker
    - privileged
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.19-dind
  image: docker:20.10.19
  before_script:
    - export DOCKER_BUILDKIT=0
    - export PROGRESS_NO_TRUNC=1

# TODO run this only on merge requests
test:
  extends: .docker
  script:
    - cp $DOCKER_GIT_CONFIG /root/.gitconfig
    - apk add git composer docker-compose build-base
    - git clone https://gitlab.metaways.net/tine20/tine20.git tine20
    - cd tine20/tine20
    - git checkout ${TINE20_BRANCH}
    - composer install --ignore-platform-reqs
    - cd $CI_PROJECT_DIR
    - echo '{"composeFiles":["lessLogs"]}' > pullup.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - composer install
    - ./console docker:pull
    - ./console docker:start
    - ./console tine:awaitdb
    - ./console tine:install
    - ./console tine:test -e nogitlabci -e nodockerci Addressbook/AllTests Tinebase/Alltests Calendar/AllTests
    - ./console tine:uninstall

githubbranch:
  script:
   - ./.gitlab/scripts/rename_images.sh
   - ./.gitlab/scripts/push_githup_branch.sh
  only:
    - master

# TODO run this only on master
.full_test:
  extends: .docker
  script:
    - cp $DOCKER_GIT_CONFIG /root/.gitconfig
    - apk add git composer npm docker-compose build-base
    - git clone https://gitlab.metaways.net/tine20/tine20.git tine20
    - cd tine20/tine20
    - git checkout ${TINE20_BRANCH}
    - composer install --ignore-platform-reqs
    - cd Tinebase/js
    - npm install
    - cd $CI_PROJECT_DIR
    - git clone https://gitlab.metaways.net/tine20/documentPreview.git docservice
    - cd docservice
    - composer install --ignore-platform-reqs --no-plugins
    - cd $CI_PROJECT_DIR
    - echo '{"composeFiles":["webpack","docservice","pma","xdebug","spam", "lessLogs"]}' > pullup.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - composer install
    - ./console docker:pull
    - ./console docker:start
    - ./console tine:awaitdb
    - ./console tine:install
    - ./console tine:test -e nogitlabci -e nodockerci Addressbook/AllTests Tinebase/Alltests Calendar/AllTests
    - ./console tine:uninstall
  only:
    - master