cache:
  untracked: true

stages:
  - prepare
  - build
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - mkdir tine20 && mkdir tine20/tine20 && mkdir tine20/tests && mkdir tine20/scripts
    - touch tine20/tine20/.gitkeep && touch tine20/tests/.gitkeep && touch tine20/scripts/.gitkeep

build:
 stage: build
 script:
   - docker-compose -f docker-compose.yml -f compose/mailstack.yml -f compose/mailstack-build.yml -f compose/web-build.yml -f compose/docservice.yml -f compose/docservice-build.yml build
   
test:
 stage: test
 script:
   - bash dockerfiles/testDockerfile.sh
   
deploy:
 stage: deploy
 only:
  refs:
    - master
 script:
   - docker-compose -f docker-compose.yml -f compose/mailstack.yml -f compose/mailstack-build.yml -f compose/web-build.yml -f compose/docservice.yml -f compose/docservice-build.yml push