version: '2'
services:
  db:
    image: mariadb:10.4.1
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: &MYSQL_DATABASE "${MYSQL_DATABASE}"
      MYSQL_USER: &MYSQL_USER "${MYSQL_USER}"
      MYSQL_PASSWORD: &MYSQL_PASSWORD "${MYSQL_PASSWORD}"
    networks:
      - internal_network

  cache:
    image: redis:5.0.5
    networks:
      - internal_network

  web:
    image: dockerregistry.metaways.net/tine20/tine20/dev:2020.11-7.4-fpm-alpine
    depends_on:
      - db
      - cache
    environment:
      TINE20_DATABASE_HOST: db
      TINE20_DATABASE_DBNAME: *MYSQL_DATABASE
      TINE20_DATABASE_USERNAME: *MYSQL_USER
      TINE20_DATABASE_PASSWORD: *MYSQL_PASSWORD
      TINE20_SETUPUSER_USERNAME: tine20setup
      TINE20_SETUPUSER_PASSWORD: tine20setup
      TINE20_LOGIN_USERNAME: tine20admin
      TINE20_LOGIN_PASSWORD: tine20admin
      TINE20_ADMIN_EMAIL: tine20admin@mail.test
      TINE20_CACHING_BACKEND: Redis
      TINE20_CACHING_REDIS_HOST: cache
      TINE20_SESSION_BACKEND: Redis
      TINE20_SESSION_HOST: cache
      TINE20_CREDENTIALCACHESHAREDKEY: change_me
      TINE20_ACCEPTED_TERMS_VERSION: 0
      TINE20_BUILDTYPE: DEVELOPMENT
      TINE20_APPLICATION_TO_INSTALL: all
      TINE20_INSTALL: "false"
    volumes:
      - ./tine20/tine20:/usr/share/tine20/:ro
      - ./tine20/tests:/usr/share/tests/:ro
      - ./tine20/scripts:/usr/share/scripts/:ro
    networks:
      - external_network
      - internal_network
    ports:
      - "4000:80"
      - "4001:10443"

networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.118.0.0/16
