version: '2'
services:

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: m4ru5ja
      MYSQL_DATABASE: &mysqldb tine20
      MYSQL_USER: &mysqluser tine20
      MYSQL_PASSWORD: &mysqlpw tine20pw

  cache:
    image: redis:latest
    container_name: cache

  web:
    image: tine20:latest
    # if you don't want webpack to run, you need to comment out the lines below "# add startup config for webpack"
    #  in the Dockerfile and build a tine20-cli image with this command: "docker build . -t tine20-cli"
    #image: tine20-cli:latest
    container_name: tine20
    volumes:
      # tine20 source!!!! Mount it under /tine/tine20
      - ./tine20/tine20:/tine/tine20/

      # tine20 file storage!!!! Mount it under /tine/files/
      - tine20_files:/tine/files/

      # mount nginx config
      - ./configs/nginx/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro

      # mount customers config
      - ./configs/customers/:/tine/customers:ro

      # tine20 tests!!!! Mount it under /tine/tests
      - ./tine20/tests/:/tine/tests/:ro

      # tine20 scripts Mount it under /tine/scripts
      - ./tine20/scripts:/tine/scripts/:ro

      # mount supervisor webpack config
      - ./configs/supervisor/webpack.conf:/etc/supervisor/conf.d/webpack.conf:ro

      # mount tine20 config.inc.php
      - ./configs/localhost/config.inc.php:/tine/tine20/config.inc.php

      # keep history (see https://stackoverflow.com/questions/28279862/docker-and-bash-history)
      # i have no idea why this is "ash_history" in the image ...
      # maybe you have to do "touch ~/.dockerweb_bash_history" before this works correctly
      - ~/.dockerweb_bash_history:/root/.ash_history

    ports:
      - "4000:80"      # tine
      - "4001:10443"   # webpack
    environment:
      TINE20_DBHOST: db
      TINE20_DBNAME: *mysqldb
      TINE20_DBUSER: *mysqluser
      TINE20_DBPASSWD: *mysqlpw
      TINE20_SETUPUSER: tine20setup
      TINE20_SETUPPASSWD: tine20setup
      TINE20_ADMINUSER: test
      TINE20_ADMINPASSWD: test
      TINE20_REDISHOST: cache

networks:
    default:
      driver: bridge

volumes:
  # DB storage
  mariadb_data:

  # Volume for tine20 file storage
  tine20_files:
