version: '2'
services:

  db:
    image: mariadb:10.4.1
    container_name: db
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: &mysqldb "${MYSQL_DATABASE}"
      MYSQL_USER: &mysqluser "${MYSQL_USER}"
      MYSQL_PASSWORD: &mysqlpw "${MYSQL_PASSWORD}"

  cache:
    image: redis:5.0.5
    container_name: cache

  web:
    image: tine20-docker-registry.mws-hosting.net/tine20:1.0.2
    container_name: tine20
    volumes:
      # tine20 source - Mount it under /tine/tine20
      - ./tine20/tine20:/tine/tine20:ro

      # tine20 file storage - Mount it under /tine/files/
      - tine20_files:/tine/files/

      # mount nginx config
      - ./configs/nginx/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro

      # mount customers config
      - ./configs/customers/:/tine/customers:ro

      # tine20 tests - Mount it under /tine/tests
      - ./tine20/tests/:/tine/tests/:ro

      # tine20 scripts Mount it under /tine/scripts
      - ./tine20/scripts:/tine/scripts/:ro
 
      # keep history (see https://stackoverflow.com/questions/28279862/docker-and-bash-history)
      # i have no idea why this is "ash_history" in the image ...
      # maybe you have to do "touch ~/.dockerweb_bash_history" before this works correctly
      - ~/.dockerweb_bash_history:/root/.ash_history

    ports:
      - "4000:80"      # tine
      - "4001:10443"   # webpack
    environment:
      TINE20_DBHOST: db
      TINE20_DBNAME: *mysqldb
      TINE20_DBUSER: *mysqluser
      TINE20_DBPASSWD: *mysqlpw
      TINE20_SETUPUSER: tine20setup
      TINE20_SETUPPASSWD: tine20setup
      TINE20_ADMINUSER: tine20admin
      TINE20_ADMINPASSWD: tine20admin
      TINE20_REDISHOST: cache

networks:
  default:
    driver: bridge

volumes:
  # DB storage
  mariadb_data:

  # Volume for tine20 file storage
  tine20_files:
