version: '3'
name: "tine20"
services:
  db:
    image: mariadb:10.4.1
    command: --max-allowed-packet=209715210
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: &MYSQL_DATABASE "${MYSQL_DATABASE}"
      MYSQL_USER: &MYSQL_USER "${MYSQL_USER}"
      MYSQL_PASSWORD: &MYSQL_PASSWORD "${MYSQL_PASSWORD}"
    networks:
      - internal_network

  cache:
    image: redis:5.0.5
    networks:
      - internal_network

  web:
    image: ${WEB_IMAGE}
    depends_on:
      - db
      - cache
    environment:
      TINE20_DATABASE_HOST: db
      TINE20_DATABASE_DBNAME: *MYSQL_DATABASE
      TINE20_DATABASE_USERNAME: *MYSQL_USER
      TINE20_DATABASE_PASSWORD: *MYSQL_PASSWORD
      TINE20_DATABASE_TABLEPREFIX: ${TINE20_DATABASE_TABLEPREFIX:-tine20_}
      TINE20_SETUPUSER_USERNAME: tine20setup
      TINE20_SETUPUSER_PASSWORD: tine20setup
      TINE20_LOGIN_USERNAME: tine20admin
      TINE20_LOGIN_PASSWORD: tine20admin
      TINE20_ADMIN_EMAIL: tine20admin@mail.test
      TINE20_CACHING_BACKEND: Redis
      TINE20_CACHING_REDIS_HOST: cache
      TINE20_SESSION_BACKEND: Redis
      TINE20_SESSION_HOST: cache
      TINE20_ACTIONQUEUE_HOST: cache
      TINE20_CREDENTIALCACHESHAREDKEY: change_me
      TINE20_ACCEPTED_TERMS_VERSION: 0
      TINE20_INSTALL_LANG: de
      TINE20_BUILDTYPE: DEVELOPMENT
      TINE20_APPLICATION_TO_INSTALL: all
      TINE20_INSTALL: "false"
      TINE20_LOGGER_PRIORITY: "7"
      TINE20_ACTIONQUEUE: "false"
      TINE20_LICENSE_PATH: /usr/share/tests/tine20/Tinebase/License/license_contract_MW-TEST-2.0.pem
    volumes:
      - ./tine20/tine20:/usr/share/tine20/:ro
      - ./tine20/tests:/usr/share/tests/:ro
      - ./tine20/scripts:/usr/share/scripts/:ro
      - ./configs/conf.d/custom.inc.php:/etc/tine20/conf.d/custom.inc.php:ro
      - ./configs/default/cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./configs/default/key.pem:/etc/nginx/certs/key.pem:ro
      # keep history (see https://stackoverflow.com/questions/28279862/docker-and-bash-history)
      # i have no idea why this is "ash_history" in the image ...
      # you have to do "touch ~/.dockerweb_bash_history" before this works correctly
      - ~/.dockerweb_bash_history:/root/.ash_history

    networks:
      - external_network
      - internal_network
    ports:
      - "4000:4000"
      - "4430:4430"

networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.118.0.0/16
