[template]
src = "dovecot-dict-sql.conf.ext.template"
dest = "/etc/dovecot/dovecot-dict-sql.conf.ext"
owner = "root"
group = "root"
keys = [
  "/mysql/db",
  "/mysql/user",
  "/mysql/password",
  "/mysql/host",
]