# this is a override file to add a broadcasthub-dev container
version: '2'
services:
  broadcasthub-service:
    image: node:14
    container_name: broadcasthub-dev
    ports:
      - "6000:80"
    environment:
      REDIS_URL: redis://cache:6379
      REDIS_CHANNEL: broadcasthub
      WS_PORT: 80
      TINE20_JSON_API_URL: http://web:4000/index.php?requestType=JSON
      TINE20_BROADCAST_CHANNEL: broadcasthub
      DEBUG_DEFAULT_LOGGING: "on"
      DEBUG_LOG_TO_FILE: "off"
      DEBUG_LOG_FILE: ../../stdout.log
      TEST_INTEGRATION_WS_URL: ws://broadcasthub:80
      TEST_E2E_WS_URL: ws://broadcasthub:80
      DEBUG: Tine20Broadcasthub:*
    networks:
      - external_network
      - internal_network
    volumes:
      - ./broadcasthub:/usr/src/app
    working_dir: /usr/src/app
    command: [ "node_modules/.bin/nodemon", "app.js" ]
