# this is a override file to add a broadcasthub container
version: '2'
services:
  web:
    volumes:
      - ./configs/broadcasthub/broadcasthub.inc.php:/etc/tine20/conf.d/broadcasthub.inc.php:ro
  broadcasthub-service:
    image: dockerregistry.metaways.net/tine20/docker/tine20-broadcasthub:0.2
    container_name: broadcasthub
    ports:
      - "4003:80"
    environment:
      REDIS_URL: redis://cache:6379
      REDIS_CHANNEL: broadcasthub
      AUTH_TIMEOUT: 5000
      WS_PORT: 80
      TINE20_JSON_API_URL: http://web:4000/index.php?requestType=JSON
      TINE20_BROADCAST_CHANNEL: broadcasthub
      DEBUG_DEFAULT_LOGGING: "on"
      DEBUG_LOG_TO_FILE: "off"
      DEBUG_LOG_FILE: ../../stdout.log
      TEST_INTEGRATION_WS_URL: ws://broadcasthub:80
      TEST_E2E_WS_URL: ws://broadcasthub:80
    networks:
      - external_network
      - internal_network