# this is a override file to add a clamav container
version: '3'
services:
  clamav:
    image: tiredofit/clamav
    container_name: clamav
    environment:
      - ZABBIX_HOSTNAME=clamav
    # need to be created on the host
    volumes:
      - ./data/clamav:/data
      #- ./logs/clamav:/var/log/clamav
    networks:
      - internal_network
