# this is a override file to add a docservice container
version: '2'
services:
  document-preview:
    image: tinegroupware/document-preview-service:2.1.994783a
    container_name: docservice
    ports:
      - "4050:80"
    networks:
      - internal_network
  web:
    volumes:
      # mount supervisor worker config
      - ./configs/docservice/docservice.inc.php:/etc/tine20/conf.d/docservice.inc.php:ro
