# this is a override file to add a docservice container
version: '2'
services:
  document-preview:
    image: tine20-docker-registry.mws-hosting.net/docservice:1.0.0
    container_name: docservice
    ports:
      - "5000:80"
    volumes:
      - ./docservice/:/document-preview/document-preview:ro
      - ./docservice/docker/configs/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro
      - ./docservice/docker/configs/sample_config.php:/etc/documentPreviewService/VERSION/config.php:ro
    environment:
        PHP_IDE_CONFIG: "serverName=documentPreview"
        #XDEBUG_CONFIG: "remote_host=192.168.33.1 remote_enable=on remote_port=9000"
  web:
    volumes:
      # mount supervisor worker config
      - ./configs/conf.d/docservice.inc.php:/tine/conf.d/docservice.inc.php:ro
