version: '2'
services:
  postfix:
    image: dockerregistry.metaways.net/tine20/docker/postfix:1.0.0
    environment:
      MYSQL_HOST: db
      MYSQL_DB: &postfixdb postfix
      MYSQL_USER: &mysqluser "${MYSQL_USER}"
      MYSQL_PASSWORD: &mysqlpw "${MYSQL_PASSWORD}"
    depends_on:
      - db
    #ports:
    #  - "25:25"
    #  - "587:587"
    #  - "465:465"

  dovecot:
    image: dockerregistry.metaways.net/tine20/docker/dovecot:1.0.1
    environment:
      MYSQL_HOST: db
      MYSQL_DB: &dovecotdb dovecot
      MYSQL_USER: *mysqluser
      MYSQL_PASSWORD: *mysqlpw
    depends_on:
      - db
    #ports:
    #  - "143:143"
    #  - "110:110"
    #  - "993:993"
    #  - "995:995"

  mailstack:
    image: dockerregistry.metaways.net/tine20/docker/mailstackcontrol:1.0.2
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: *mysqluser
      MYSQL_PASSWORD: *mysqlpw
      DOVECOT_DATABASE: *dovecotdb
      POSTFIX_DATABASE: *postfixdb