version: '2'
services:
  postfix:
    build:
      context: dockerfiles/mailstack/postfix
    image: tine20-docker-registry.mws-hosting.net/postfix:latest

  dovecot:
    build:
      context: dockerfiles/mailstack/dovecot
    image: tine20-docker-registry.mws-hosting.net/dovecot:latest

  mailstack:
    build:
      context: dockerfiles/mailstack/control
    image: tine20-docker-registry.mws-hosting.net/mailstackcontrol:latest
