version: '2'
services:
  postfix:
    build:
      context: dockerfiles/mailstack/postfix

  dovecot:
    build:
      context: dockerfiles/mailstack/dovecot

  mailstack:
    build:
      context: dockerfiles/mailstack/control
