# use mysql instead of mariadb
version: '2'
services:
  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: &mysqldb "${MYSQL_DATABASE}"
      MYSQL_USER: &mysqluser "${MYSQL_USER}"
      MYSQL_PASSWORD: &mysqlpw "${MYSQL_PASSWORD}"
    # see https://github.com/docker-library/mysql/issues/422
    security_opt:
      - seccomp:unconfined
    networks:
      - internal_network
