# this is a override file to add a phpldapadmin container
services:

  pla:
    image: osixia/phpldapadmin:0.9.0
    container_name: pla
    ports:
      - "4007:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - external_network
      - internal_network
