# this is a override file to add a phpmyadmin container
version: '2'
services:

  pma:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: pma
    ports:
      - "4002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - external_network
      - internal_network