# run this with
# $ docker-compose -f docker-compose.yml -f compose/worker.yml up
version: '2'
services:
  web:
    image: tine20:latest
    container_name: tine20
    volumes:
    # mount supervisor webpack config
    - ./configs/supervisor/webpack.conf:/etc/supervisor/conf.d/webpack.conf:ro 
