# run this with
# $ docker-compose -f docker-compose.yml -f compose/worker.yml up
version: '3'
services:
  web:
    volumes:
      - ./configs/default/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./configs/webpack/webpack.inc.php:/etc/tine20/conf.d/webpack.inc.php

  webpack:
    image: ${WEBPACK_IMAGE:-node:18.9.0-alpine}
    ports:
      - "10443:10443"
    depends_on:
      - web
    networks:
      - external_network
      - internal_network
    volumes:
      - ./tine20/tine20:/usr/share/tine20/:ro
    command: "npm --prefix /usr/share/tine20/Tinebase/js/ start"
