# run this with
# $ docker-compose -f docker-compose.yml -f compose/worker.yml up
version: '2'
services:
  web:
    image: tine20:latest
    container_name: tine20
    volumes:
      # mount supervisor worker config
      - ./configs/supervisor/worker.conf:/etc/supervisor/conf.d/worker.conf:ro
            # mount tine20 config.inc.php
      - ./configs/localhost/actionQueue.ini:/tine/tine20/actionQueue.ini:ro
